[workspace]
authors = ["James Wilson <james@snapxr.io>"]
channels = ["conda-forge"]
name = "unit03_hw"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.2,<3"
pandas = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.30.1,<7"
jupyterlab = ">=4.4.6,<5"
